pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // 必须添加此源以获取 LibXposed API
        maven { url 'https://api.xposed.info/' }
    }
}
rootProject.name = "MiPlayFix"
include ':app'