plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.miplayfix'
    compileSdk 34

    defaultConfig {
        applicationId "com.xposed.miplayfix"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // 官方标准 API，绝对不会报错！
    compileOnly 'de.robv.android.xposed:api:82'
}
