plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.miplayfix'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.miplayfix"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly(libs.libxposed.api)
    implementation(libs.libxposed.service)
    compileOnly "androidx.annotation:annotation:1.7.1"
}